export declare const NEWSLETTER_QUERY_IDS: Record<string, string>;
export declare const XWA_PATHS: Record<string, string>;
export declare function isJidNewsletter(jid: string): boolean;
export declare function normalizeNewsletterJid(id: string): string;
export declare function extractNewsletterMetadata(node: any, isCreate?: boolean): any;
export declare function normalizeNewsletterMsg(msg?: any): any;
export declare function patchSocketNewsletterEvents(sock: any): any;
export declare function makeNewsletterHelper(sock: any): any;
export declare function patchBaileysNewsletterMediaRc13_FORCE(): any;
export declare function isNewsletterJid(value?: string): boolean;
export declare function extractInviteCode(input?: string): string;
export declare function getOwnerChannelLink(): string;
export declare function getOwnerChannelJidFallback(): string;
export declare function getNewsletterHelper(sock: any): any;
export declare function attachNewsletterFeatures(sock: any): any;
export declare function resolveChannelTarget(sock: any, input: string, newsletter?: any): Promise<string>;
export declare function resolveOwnerChannelJid(sock: any, newsletter?: any): Promise<string>;
export declare function clearChannelTargetCache(): void;
export declare function sendInteractive(sock: any, toJid: string, content?: any, options?: any): Promise<any>;
export declare const sendButtons: typeof sendInteractive;
export declare function unwrapChannelMessage(message: any): any;
export declare function getQuotedAndContextInfo(m: any): any;
export declare function handleIdChannel(ctx: any): Promise<void>;
export declare function handleListChannel(ctx: any): Promise<void>;
export declare function handleToChannel(ctx: any): Promise<void>;
export declare function handlePtvChannel(ctx: any): Promise<void>;
export declare function handleUpChannel(ctx: any): Promise<void>;
export declare function upch(sock: any, target: string, input: any, options?: any): Promise<any>;
export declare function toch(sock: any, target: string, input: any, options?: any): Promise<any>;
export declare function ptvch(sock: any, target: string, input: any, options?: any): Promise<any>;
