export declare const VERSION = "4.4";
export declare const NIXCODE_VERSION: string;
type PlainObject = Record<string, any>;
export declare class BaseBuilder {
  setTitle(title: string): this;
  setSubtitle(subtitle: string): this;
  setBody(body: string): this;
  setFooter(footer: string): this;
  setContextInfo(obj: PlainObject): this;
  addPayload(obj: PlainObject): this;
  static resize(buffer: Buffer, x: number, y: number, fit?: string): Promise<Buffer>;
  static fetchBuffer(url: string, options?: any, config?: any): Promise<Buffer>;
}
export declare class Button extends BaseBuilder {
  constructor(client: any);
  setVideo(path: any, options?: PlainObject): this;
  setImage(path: any, options?: PlainObject): this;
  setDocument(path: any, options?: PlainObject): this;
  addHeader(type?: string | PlainObject, options?: PlainObject): this;
  addheader(type?: string | PlainObject, options?: PlainObject): this;
  setMedia(obj: PlainObject): this;
  clearButtons(): this;
  setParams(obj?: PlainObject): this;
  setLimitedOffer(input?: PlainObject): this;
  clearLimitedOffer(): this;
  addButton(name: string, params?: any): this;
  addbutton(name: string, params?: any): this;
  addBookingConfirmation(params?: PlainObject): this;
  addBooking(params?: PlainObject): this;
  makeRow(header?: string, title?: string, description?: string, id?: string): this;
  makeSection(title?: string, highlight_label?: string): this;
  makeSections(title?: string, highlight_label?: string): this;
  addSelection(title: string, options?: PlainObject): this;
  addReply(display_text?: string, id?: string, options?: PlainObject): this;
  addCall(display_text?: string, id?: string, options?: PlainObject): this;
  addReminder(display_text?: string, id?: string, options?: PlainObject): this;
  addCancelReminder(display_text?: string, id?: string, options?: PlainObject): this;
  addAddress(display_text?: string, id?: string, options?: PlainObject): this;
  addLocation(options?: PlainObject): this;
  addUrl(display_text?: string, url?: string, webview_interaction?: boolean, options?: PlainObject): this;
  addCopy(display_text?: string, copy_code?: string, options?: PlainObject | string): this;
  toCard(): Promise<any>;
  build(jid: string, options?: PlainObject): Promise<any>;
  send(jid: string, options?: PlainObject): Promise<any>;
}
export declare const Message: typeof Button;
export declare const NativeButton: typeof Button;
export declare class ButtonV2 extends BaseBuilder {
  constructor(client: any);
  addButton(displayText?: string, buttonId?: string, options?: PlainObject | string): this;
  addRawButton(obj: PlainObject): this;
  setParams(obj?: PlainObject): this;
  addNativeButton(name: string, params?: any): this;
  addNativeReply(display_text?: string, id?: string): this;
  addUrl(display_text?: string, url?: string, webview_interaction?: boolean): this;
  addCopy(display_text?: string, copy_code?: string, id?: string): this;
  addCall(display_text?: string, id?: string): this;
  addLocation(display_text?: string, id?: string): this;
  addSelection(title?: string, sections?: any[], id?: string, displayText?: string): this;
  addBottomSheet(displayText?: string, title?: string, sections?: any[], id?: string): this;
  setThumbnail(path: any): this;
  setLocationMessage(obj?: PlainObject): this;
  setMedia(obj: PlainObject): this;
  buildNative(jid: string, options?: PlainObject): Promise<any>;
  buildOld(jid: string, options?: PlainObject): Promise<any>;
  build(jid: string, options?: PlainObject): Promise<any>;
  send(jid: string, options?: PlainObject): Promise<any>;
}
export declare class Carousel extends BaseBuilder {
  constructor(client: any);
  addCard(card: any | any[]): this;
  build(jid: string, options?: PlainObject): any;
  send(jid: string, options?: PlainObject): Promise<any>;
}
export declare class AIRich {
  constructor(client: any);
  setTitle(title: string): this;
  addText(text: string, options?: { hyperlink?: boolean; citation?: boolean; latex?: boolean }): this;
  addLatex(text: string, items?: any[]): this;
  addCode(language: string, code: string): this;
  addTable(table: string[][]): this;
  addSource(sources?: string[] | string[][]): this;
  addReels(reelsItems?: PlainObject | PlainObject[]): this;
  addImage(imageUrl: string | string[]): this;
  build(options?: PlainObject): any;
  send(jid: string, options?: PlainObject): Promise<any>;
  static tokenizer(code: string, lang?: string): any;
  static toTableMetadata(arr: string[][]): any;
}
export declare class Swgc {
  constructor(client: any);
  target(jid: string): this;
  setTarget(jid: string): this;
  text(value: string): this;
  image(buffer: Buffer, caption?: string): this;
  video(buffer: Buffer, caption?: string): this;
  audio(buffer: Buffer, options?: PlainObject): this;
  media(input: any, kind?: string, options?: PlainObject): this;
  fromInput(message: any, text?: string): Promise<this>;
  setOptions(options?: PlainObject): this;
  send(targetJid?: string, options?: PlainObject): Promise<any>;
}
export declare class StickerPack extends BaseBuilder {
  constructor(client: any);
  setPackName(name?: string): this;
  setPackname(name?: string): this;
  setName(name?: string): this;
  setAuthor(author?: string): this;
  setPublisher(author?: string): this;
  setDescription(description?: string): this;
  setCaption(caption?: string): this;
  setCover(cover?: any): this;
  setThumbnail(thumbnail?: any): this;
  addSticker(input: any, options?: PlainObject): this;
  addStickers(stickers?: any[]): this;
  setStickers(stickers?: any[]): this;
  addImage(input: any, options?: PlainObject): this;
  addVideo(input: any, options?: PlainObject): this;
  addAnimated(input: any, options?: PlainObject): this;
  setOrigin(value?: number): this;
  toJSON(): PlainObject;
  prepare(options?: PlainObject): Promise<any>;
  send(jid: string, options?: PlainObject): Promise<any>;
}
export declare function sendButtons(sock: any, toJid: string, content?: PlainObject, options?: PlainObject): Promise<any>;
export declare function imageToWebp(media: Buffer, options?: PlainObject): Promise<Buffer>;
export declare function videoToWebp(media: Buffer, options?: PlainObject): Promise<Buffer>;
export declare function writeExif(media: Buffer, metadata?: PlainObject): Promise<Buffer>;
export declare function writeExifImg(media: Buffer, metadata?: PlainObject): Promise<Buffer>;
export declare function writeExifVid(media: Buffer, metadata?: PlainObject): Promise<Buffer>;
export declare function getStickerTriggerFromMessage(message: any): string;
export declare function setStickerTrigger(input: any, trigger?: string): Promise<any>;
export declare function updateStickerWmOnly(input: any, metadata?: PlainObject): Promise<Buffer>;
export declare function detectAlbumMessage(message: any): boolean;
export declare function isAlbumReply(message: any): boolean;
export declare function getAlbumKeyInfo(message: any): any;
export declare function prepareStickerPackMessage(sock: any, stickerPack: any, options?: PlainObject): Promise<any>;
export declare function sendStickerPack(sock: any, jid: string, stickerPack: any, options?: PlainObject): Promise<any>;
export declare function patchSocketStickerPack(sock: any): any;
export declare function makeStickerHelper(sock: any): any;
export declare function sendStickerPackLink(sock: any, jid: string, code?: string, options?: PlainObject): Promise<any>;
export declare function patchBaileysStickerPackMediaRc13_FORCE(): any;
export declare function autoPatchBaileysStickerPackMediaRc13_FORCE(): any;
export declare function patchBaileysForSwgc(): any;
export declare function patchSocketSwgc(sock: any): any;
export declare function sendSwgc(sock: any, groupJid: string, input: any, options?: PlainObject): Promise<any>;
export declare function createStatusPayloadFromInput(message: any, text?: string): Promise<PlainObject | null>;
export declare function payloadToStatusContent(payload: PlainObject, config?: PlainObject): PlainObject | null;
export declare function sendPayloadToGroupStatus(sock: any, groupJid: string, payload: PlainObject, options?: PlainObject): Promise<any>;
export declare function groupStatus(sock: any, groupJid: string, content: PlainObject, options?: PlainObject): Promise<any>;
export declare function notifySwgcEcho(sock: any, msg: any): void;
export declare function waitForSwgcEcho(sock: any, groupJid: string, messageId: string, timeoutMs?: number): Promise<any>;
export declare function hasGroupStatusEnvelope(message: any): boolean;
export declare function buildGroupList(sock: any, options?: PlainObject): Promise<any[]>;
export declare function makeGroupListText(groups: any[], prefix?: string): string;
export declare function resolveGroupTarget(sock: any, msg: any, targetText?: string, options?: PlainObject): Promise<string>;
export declare function splitTargetAndContent(text?: string): { target: string; content: string };
export declare function isGroupAdmin(sock: any, groupJid: string, jid?: string): Promise<boolean>;
export declare function getBodyText(message: any): string;
export declare function normalizeLimitOfferInput(input?: PlainObject): any;
export declare function buildLimitedOfferParam(input?: PlainObject): any;
export declare function sendCarouselWithLimitOffer(sock: any, jid: string, content?: PlainObject, options?: PlainObject): Promise<any>;
export declare const sendInteractiveCardLimitOffer: typeof sendCarouselWithLimitOffer;
export declare function buildBookingConfirmationParams(input?: PlainObject): PlainObject;
export { };
