export declare const DEFAULT_CUSTOM_PAIRING_CODE = "NATASSBZ";
export declare function onlyNumber(value?: string): string;
export declare function normalizePhoneNumber(number?: string): string;
export declare function normalizeCustomPairingCode(code?: string, length?: number): string | null;
export declare function formatPairingCode(code?: string): string;
export declare function sleep(ms?: number): Promise<unknown>;
export declare function requestCustomPairingCode(sock: any, state?: null, options?: {}): Promise<any>;
export declare const requestNatasssPairingCode: typeof requestCustomPairingCode;
export declare function waitForQrPairing(sock: any, options?: {}): Promise<unknown>;
export declare function pairing(sock: any, type?: number, options?: {}): Promise<any>;
export default pairing;
